sudo: required
language: ruby

services:
- docker

script:
- docker build -t slashgear/citation-base .

after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
- docker push slashgear/citation-base